trigger:
  batch: true
  branches:
    include:
      - dev

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: GenerateDevDocSite
    strategy:
      matrix:
        Python38:
          python.version: '3.8'
    steps:
      - task: usePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - template: templates/build.yaml
      - task: AzureCLI@2
        displayName: Upload files to Azure Storage Account
        inputs:
          azureSubscription: choreo-docs-site-rg
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob sync -c '$web/choreo/docs' --account-name "choreodocsdevstorage" -s "$(Build.ArtifactStagingDirectory)/dist/en/"
            az cdn endpoint purge -g choreo-docs-site-rg -n choreodocssitedev --profile-name choreo-docs-dev-cdn --no-wait --content-paths '/*'
